### ISSUE TITLE
invalid functools dependency

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-oaiserver#112]
**Problem:**
It is currently not possible to install invenio-oaiserver v1.0.0a11 with python 3.

**Scenario:**
```sh
$ python --version
Python 3.5.0

$ cat requirements.txt
invenio-oaiserver==1.0.0a11

$ pip install -r requirements.txt
Collecting invenio-oaiserver==1.0.0a11 (from -r requirements.txt (line 1))
  Using cached invenio_oaiserver-1.0.0a11-py2.py3-none-any.whl
Collecting lxml>=3.5.0 (from invenio-oaiserver==1.0.0a11->-r requirements.txt (line 1))
Collecting Flask-BabelEx>=0.9.2 (from invenio-oaiserver==1.0.0a11->-r requirements.txt (line 1))
Collecting functools32>=3.2.3-2 (from invenio-oaiserver==1.0.0a11->-r requirements.txt (line 1))
  Using cached functools32-3.2.3-2.zip
    Complete output from command python setup.py egg_info:
    This backport is for Python 2.7 only.
```

This however works with python 2.7

This worked with invenio-oaiserver v1.0.0a9. Version 1.0.0a10 has the same issue.

This might come from a bug added in [this commit](https://github.com/inveniosoftware/invenio-oaiserver/commit/7b48f9bca6813f9176f3dcd217fb77e65b4df7bf#diff-2eeaed663bd0d25b7e608891384b7298R89).

It looks like [the issue described here](https://hynek.me/articles/conditional-python-dependencies/).

**Comment by hachreak** [comment]
I think @krzysztof had the same problem.
But I don't remember which module was.

**Comment by nharraud** [comment]
@hachreak `invenio-oaiserver` requires `functools32-3.2.3-2` for python 2. The problem seems to be that the condition, i.e. only for python 2, is ignored when the wheel file is created. Thus it is required for python 3 too. As functools32 is only compatible with python 2 the install fails.

**Comment by hachreak** [comment]
Ok, sorry, now I know which module was. It was this module actually. XD

**Comment by nharraud** [comment]
Reverting the changes of commit 7b48f9bca6813f9176f3dcd217fb77e65b4df7bf concerning functools32 seems to fix the issue.

I tested like this:
```sh
# in python 2 env
$ git diff
diff --git a/setup.py b/setup.py
index b6119b7..02637d6 100644
--- a/setup.py
+++ b/setup.py
@@ -48,6 +48,9 @@ tests_require = [
 ]

 extras_require = {
+    ':python_version=="2.7"': [
+        'functools32>=3.2.3',
+    ],
     'admin': [
         'Flask-Admin>=1.3.0',
     ],
@@ -86,7 +89,7 @@ install_requires = [
     'dojson>=1.2.0',
     'elasticsearch>=2.0.0,<3.0.0',
     'elasticsearch-dsl>=2.0.0,<3.0.0',
-    'functools32>=3.2.3-2; python_version=="2.7"',
+    # 'functools32>=3.2.3-2; python_version=="2.7"',
     'invenio-pidstore>=1.0.0b1',
     'invenio-query-parser>=0.6.0',
     'invenio-records>=1.0.0b1',

$  python ./setup.py bdist_wheel

# in python 3 env
pip install .../invenio_oaiserver-1.0.0a11-py2.py3-none-any.whl
# where the .whl file is the one generated with python 2
```

@krzysztof what was the reason of the change? Can we revert it?

**Comment by krzysztof** [comment]
Reverting would still cause errors, take a look at failing master branch of invenio-collections: https://travis-ci.org/inveniosoftware/invenio-collections/jobs/196664315

If this was reverted, this PR would not pass through travis just as invenio-collections is failing right now.

This used to work before because versions markers were ignored by the requirements-builder < 0.2.2 and some version of setuptools, so specifying the version markers didn't do anything. functools32 even if not specified explicitly in dependencies, will still be fetched through ``invenio-records`` -> ``jsonschema`` dependency chain:
```
...
Collecting functools32; python_version == "2.7" (from jsonschema>=2.5.1->invenio-records>=1.0.0b1->invenio-oaiserver==1.0.0a11)
```

That's how Invenio-JSONSchemas is getting away with it, i.e.: by not specifying functools32 in the dependencies: https://github.com/inveniosoftware/invenio-jsonschemas/search?utf8=%E2%9C%93&q=functools32

I would suggest removing the dependency from setup.py completely just to fix it for now, and keep this issue pinned as generic "version markers do not work" problem.

**Comment by krzysztof** [comment]
This could be finally resolved after this: https://github.com/inveniosoftware/requirements-builder/pull/27

**Comment by krzysztof** [comment]
In addition to that after release of requirements-buidler https://github.com/inveniosoftware/invenio-collections master should be restarted (it should pass).

And the functools32 dependency should be added to  https://github.com/inveniosoftware/invenio-jsonschemas

**Comment by lnielsen** [comment]
@nharraud I think this one was solved right?
