### ISSUE TITLE
response is not correct for no records

### ISSUE THREAD

**Issue by rerowep** [inveniosoftware/invenio-oaiserver#186]
If we have no records the `<ListRecords>` opening tag is missing. 

```
<?xml version=\'1.0\' encoding=\'UTF-8\'?>
<?xml-stylesheet type="text/xsl" href="/static/xsl/oai.xsl"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
  <responseDate>2020-06-02T23:00:28Z</responseDate>
  <request until="2020-06-02T23:00:28+00:00Z" from_="2020-06-02T06:00:00+00:00Z" metadataPrefix="marc21" verb="ListRecords">
    https://localhost:5000/oai2d
  </request>
  
  <ListRecords/>
</OAI-PMH>
```

**Comment by wgresshoff** [comment]
<ListRecords/> is an opening and closing tag at the same time. But in my opinion, if the response of ListRecords is empty, the should be no <ListRecords> tag at all but
<error code="noRecordsMatch"/> instead. But this is surely open for discussion, the spec is not so clear about it.

**Comment by pronguen** [comment]
If there are no records to be returned, the OAI provider should not send ListRecords response with empty contents, but `noRecordsMatch` error message.
Please see "Error and Exception Conditions" section in: http://www.openarchives.org/OAI/openarchivesprotocol.html#ErrorConditions

**Comment by jesusbagpuss** [comment]
This issue has just been reported on the [OAI-PMH Google group](https://groups.google.com/g/oai-pmh/).

A zenodo repository was failing it's validation, as the set chosen to validate against (in their case, the `openaire` set) didn't contain any records, but output an empty `<ListIdentifiers/>` element rather than the expected `<error code="noRecordsMatch"/>`.

Currently they are unable to register their OAI-PMH endpoint.
